name: Lints

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Version on our docker img

      - name: flake8
        run: |
          pip install `egrep -o 'flake8==\S+' web/requirements.txt`  # install our version of flake8
          flake8 web/ --config web/setup.cfg
          flake8 docker/pandoc-lambda/function/ --config web/setup.cfg

      - name: black
        run: |
          pip install `egrep -o 'black==\S+' web/requirements.txt`  # install our version of black
          black --check --diff . # Uses pyproject.toml

      - name: mypy
        run: |
          pip install -r web/requirements.txt
          PYTHONPATH=${PYTHONPATH}:${PWD}/web mypy web/main --config-file=web/setup.cfg
